version: '3.1'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - custom-network
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
